site_name: docSkimmer theme
site_description: An accessible skimmable theme for documentation sites built using MkDocs
site_author: Heini Fagerlund

site_url: https://hfagerlund.github.io/mkdocs-docskimmer
repo_url: https://github.com/hfagerlund/mkdocs-docskimmer/

nav:
    - Intro: index.md
    - Examples:
        - Sample1: examples/sample-page.md
        - Sample2: examples/another-sample-page.md

theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

extra:
    version: 0.4.0

copyright: Copyright &copy; 2017 Heini Fagerlund
google_analytics: ['UA-38407980-4', 'auto']
